services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: careerly
      POSTGRES_PASSWORD: careerly
      POSTGRES_DB: careerly
    ports:
      - "5432:5432"
    volumes:
      - careerly_pg:/var/lib/postgresql/data

volumes:
  careerly_pg:
